// GameData.cs — dati di gioco (GENERATO da data/gamedata.js). Non modificare a mano.
using System.Collections.Generic;

namespace ImperiumGalactica.Engine
{
    public static class GameData
    {
        public static List<PlanetData> Planets()
        {
            return new List<PlanetData> {
                new PlanetData { id=1, nome="Pyros", tipo="Fuoco", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=3, metallo=1, pietra=1 } },
                new PlanetData { id=2, nome="Ignis", tipo="Fuoco", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=3, metallo=2, pietra=1 } },
                new PlanetData { id=3, nome="Vulcanis", tipo="Fuoco", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=3 } },
                new PlanetData { id=4, nome="Ember", tipo="Fuoco", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=1, metallo=3, pietra=3 } },
                new PlanetData { id=5, nome="Solara", tipo="Fuoco", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=3, metallo=1, pietra=3 } },
                new PlanetData { id=6, nome="Cinder", tipo="Fuoco", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=2, metallo=1, pietra=1 } },
                new PlanetData { id=7, nome="Magmar", tipo="Fuoco", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=1 } },
                new PlanetData { id=8, nome="Helios", tipo="Fuoco", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=3, metallo=3, pietra=1 } },
                new PlanetData { id=9, nome="Glacius", tipo="Ghiaccio", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=3, metallo=1, pietra=3 } },
                new PlanetData { id=10, nome="Borealis", tipo="Ghiaccio", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=3, metallo=3, pietra=3 } },
                new PlanetData { id=11, nome="Frost", tipo="Ghiaccio", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=2, metallo=1, pietra=2 } },
                new PlanetData { id=12, nome="Cryon", tipo="Ghiaccio", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=3, metallo=2, pietra=1 } },
                new PlanetData { id=13, nome="Nivalis", tipo="Ghiaccio", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=1, metallo=3, pietra=2 } },
                new PlanetData { id=14, nome="Gelo", tipo="Ghiaccio", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=1 } },
                new PlanetData { id=15, nome="Hyperion", tipo="Ghiaccio", produttivita=2, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=1, metallo=2, pietra=1 } },
                new PlanetData { id=16, nome="Gaia", tipo="Terra", produttivita=1, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=2 } },
                new PlanetData { id=17, nome="Verdania", tipo="Terra", produttivita=1, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=2 } },
                new PlanetData { id=18, nome="Eden", tipo="Terra", produttivita=1, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=2 } },
                new PlanetData { id=19, nome="Terranova", tipo="Terra", produttivita=1, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=2 } },
                new PlanetData { id=20, nome="Silvana", tipo="Terra", produttivita=1, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=2 } },
                new PlanetData { id=21, nome="Arbor", tipo="Terra", produttivita=1, economia=3, soldiTurno=15000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=2 } },
                new PlanetData { id=22, nome="Pratum", tipo="Terra", produttivita=1, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=2 } },
                new PlanetData { id=23, nome="Florae", tipo="Terra", produttivita=1, economia=1, soldiTurno=5000, moltMaterie=new MatMult{ carburante=2, metallo=2, pietra=2 } },
                new PlanetData { id=24, nome="Petra", tipo="Roccia", produttivita=3, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=1 } },
                new PlanetData { id=25, nome="Rocca", tipo="Roccia", produttivita=2, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=1 } },
                new PlanetData { id=26, nome="Silex", tipo="Roccia", produttivita=3, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=1 } },
                new PlanetData { id=27, nome="Monolith", tipo="Roccia", produttivita=1, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=1 } },
                new PlanetData { id=28, nome="Craggor", tipo="Roccia", produttivita=2, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=1 } },
                new PlanetData { id=29, nome="Basalt", tipo="Roccia", produttivita=1, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=1 } },
                new PlanetData { id=30, nome="Saxum", tipo="Roccia", produttivita=3, economia=2, soldiTurno=10000, moltMaterie=new MatMult{ carburante=1, metallo=1, pietra=1 } },
            };
        }

        public static List<AsteroidCard> Asteroids()
        {
            return new List<AsteroidCard> {
                new AsteroidCard { tipo="malus", unitaPerse=0 },
                new AsteroidCard { tipo="malus", unitaPerse=3 },
                new AsteroidCard { tipo="malus", unitaPerse=3 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="bonus", risorsa="pietra", quantita=3 },
                new AsteroidCard { tipo="bonus", risorsa="metallo", quantita=3 },
                new AsteroidCard { tipo="malus", unitaPerse=3 },
                new AsteroidCard { tipo="bonus", risorsa="carburante", quantita=1 },
                new AsteroidCard { tipo="bonus", risorsa="metallo", quantita=1 },
                new AsteroidCard { tipo="malus", unitaPerse=2 },
                new AsteroidCard { tipo="bonus", risorsa="metallo", quantita=2 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="malus", unitaPerse=2 },
                new AsteroidCard { tipo="bonus", risorsa="pietra", quantita=1 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="bonus", risorsa="soldi", quantita=2 },
                new AsteroidCard { tipo="bonus", risorsa="soldi", quantita=1 },
                new AsteroidCard { tipo="malus", unitaPerse=0 },
                new AsteroidCard { tipo="malus", unitaPerse=2 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="bonus", risorsa="carburante", quantita=1 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="malus", unitaPerse=2 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="bonus", risorsa="pietra", quantita=3 },
                new AsteroidCard { tipo="malus", unitaPerse=3 },
                new AsteroidCard { tipo="bonus", risorsa="pietra", quantita=0 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="bonus", risorsa="carburante", quantita=2 },
                new AsteroidCard { tipo="bonus", risorsa="soldi", quantita=2 },
                new AsteroidCard { tipo="malus", unitaPerse=0 },
                new AsteroidCard { tipo="malus", unitaPerse=0 },
                new AsteroidCard { tipo="malus", unitaPerse=1 },
                new AsteroidCard { tipo="bonus", risorsa="metallo", quantita=3 },
                new AsteroidCard { tipo="bonus", risorsa="pietra", quantita=1 },
                new AsteroidCard { tipo="bonus", risorsa="soldi", quantita=2 },
            };
        }

        public static List<MarketCard> Market()
        {
            return new List<MarketCard> {
                new MarketCard { unita="caccia", qta=1, prezzo=3000 },
                new MarketCard { unita="caccia", qta=1, prezzo=4000 },
                new MarketCard { unita="caccia", qta=1, prezzo=6000 },
                new MarketCard { unita="caccia", qta=1, prezzo=7000 },
                new MarketCard { unita="caccia", qta=2, prezzo=5000 },
                new MarketCard { unita="caccia", qta=2, prezzo=6000 },
                new MarketCard { unita="caccia", qta=2, prezzo=12000 },
                new MarketCard { unita="caccia", qta=3, prezzo=9000 },
                new MarketCard { unita="caccia", qta=3, prezzo=11000 },
                new MarketCard { unita="caccia", qta=3, prezzo=21000 },
                new MarketCard { unita="caccia", qta=3, prezzo=23000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=10000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=12000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=12000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=14000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=16000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=24000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=26000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=28000 },
                new MarketCard { unita="torpediniera", qta=1, prezzo=30000 },
                new MarketCard { unita="torpediniera", qta=2, prezzo=20000 },
                new MarketCard { unita="torpediniera", qta=2, prezzo=24000 },
                new MarketCard { unita="torpediniera", qta=2, prezzo=28000 },
                new MarketCard { unita="torpediniera", qta=2, prezzo=32000 },
                new MarketCard { unita="torpediniera", qta=2, prezzo=48000 },
                new MarketCard { unita="torpediniera", qta=2, prezzo=52000 },
                new MarketCard { unita="torpediniera", qta=2, prezzo=56000 },
                new MarketCard { unita="torpediniera", qta=2, prezzo=60000 },
                new MarketCard { unita="torpediniera", qta=3, prezzo=30000 },
                new MarketCard { unita="torpediniera", qta=3, prezzo=36000 },
                new MarketCard { unita="torpediniera", qta=3, prezzo=42000 },
                new MarketCard { unita="torpediniera", qta=3, prezzo=48000 },
                new MarketCard { unita="torpediniera", qta=3, prezzo=72000 },
                new MarketCard { unita="torpediniera", qta=3, prezzo=78000 },
                new MarketCard { unita="torpediniera", qta=3, prezzo=84000 },
                new MarketCard { unita="torpediniera", qta=3, prezzo=90000 },
                new MarketCard { unita="colonia", qta=1, prezzo=30000 },
                new MarketCard { unita="colonia", qta=1, prezzo=40000 },
                new MarketCard { unita="colonia", qta=1, prezzo=65000 },
                new MarketCard { unita="colonia", qta=1, prezzo=70000 },
                new MarketCard { unita="carri", qta=1, prezzo=5000 },
                new MarketCard { unita="carri", qta=1, prezzo=6000 },
                new MarketCard { unita="carri", qta=1, prezzo=8000 },
                new MarketCard { unita="carri", qta=1, prezzo=13000 },
                new MarketCard { unita="carri", qta=1, prezzo=14000 },
                new MarketCard { unita="carri", qta=1, prezzo=15000 },
                new MarketCard { unita="carri", qta=2, prezzo=10000 },
                new MarketCard { unita="carri", qta=2, prezzo=12000 },
                new MarketCard { unita="carri", qta=2, prezzo=24000 },
                new MarketCard { unita="carri", qta=2, prezzo=30000 },
                new MarketCard { unita="carri", qta=3, prezzo=15000 },
                new MarketCard { unita="carri", qta=3, prezzo=21000 },
                new MarketCard { unita="carri", qta=3, prezzo=36000 },
                new MarketCard { unita="carri", qta=3, prezzo=39000 },
                new MarketCard { unita="carri", qta=3, prezzo=42000 },
            };
        }
    }
}
